### ISSUE TITLE
Before conducting blastp queries against the nr database or your own database, please convert their sequence ids in the database into following ids

### ISSUE THREAD

**Issue by Snow0208** [xingxingshen/HGTfinder#1]
Dear xingxingshen,
      I have met some problems when using this pipeline. In your README txt ,you had written before conducting blastp queries against the nr database or your own database I need to convert their sequence ids in the database into the following ids, but there are no details in this step. So if I  want to convert my NCBI Reference Sequence into that format how could I do? Do you have any detailed tutorials?

![image](https://github.com/xingxingshen/HGTfinder/assets/148888724/994372a4-3575-4b21-bbb8-e790b8b71d63)

**Comment by xingxingshen** [comment]
you could use your script to convert NCBI seqID to the full information that is required to run our pipeline.
